### ISSUE TITLE
API fails to initialize with version 1.46.0

### ISSUE THREAD

**Issue by ocalvo** [jrester/tesla_powerwall#5] opened 2020-04-17 20:07 UTC
[More info](https://github.com/home-assistant/core/issues/34207#issuecomment-615437725)

**Comment by jrester** [comment] 2020-04-18 09:31
Would you mind sharing some responses from the API and the main javascript code? So I can include them I the API? The most important ones for homeassistant would be:
* `https://<powerwall-api>/api/site_info`
* `https://<powerwall-api>/api/system_status/soe`
* `https://<powerwall-api>/api/meters/aggregates`
* `https://<powerwall-api>/api/powerwalls`
* `https://<powerwall-api>/api/sitemaster`

If you feel like the response includes sensitive please consider replacing them with `XXX`.

And the main javascript code. This should be a file named something like `app.XXX.js`. In chrome you can find it in the developer console under "Sources" and in Firefox under "Debugger".

Thanks for helping!

**Comment by ocalvo** [comment] 2020-04-18 19:19
- https://tesla-gateway/api/site_info
```json
{"max_site_meter_power_kW":1000000000,
"min_site_meter_power_kW":-1000000000,
"nominal_system_energy_kWh":13.5,
"nominal_system_power_kW":15,
"max_system_energy_kWh":0,
"max_system_power_kW":0,
"site_name":"Home Energy Gateway",
"timezone":"America/Los_Angeles",
"grid_code":"60Hz_240V_s_IEEE1547a_2014",
"grid_voltage_setting":240,
"grid_freq_setting":60,
"grid_phase_setting":"Split",
"country":"United States",
"state":"Washington",
"distributor":"*",
"utility":"Puget Sound Energy",
"retailer":"*",
"region":"IEEE1547a:2014"}
```
- https://tesla-gateway/api/system_status/soe
```json
{"percentage":60.646753185128944}
```
- https://tesla-gateway/api/meters/aggregates
```json
{"site":
  {"last_communication_time":"2020-04-18T12:08:57.187708738-07:00",
  "instant_power":-5.4799957275390625,
  "instant_reactive_power":-177.02999877929688,
  "instant_apparent_power":177.11479560152986,
  "frequency":60,
  "energy_exported":468746.19806244376,
  "energy_imported":487472.18806244386,
  "instant_average_voltage":121.69499969482422,
  "instant_total_current":0,
  "i_a_current":0,
  "i_b_current":0,
  "i_c_current":0,
  "timeout":1500000000},
"battery":
  {"last_communication_time":"2020-04-18T12:08:57.19035638-07:00",
  "instant_power":-2900,
  "instant_reactive_power":20,
  "instant_apparent_power":2900.068964697219,
  "frequency":59.979,
  "energy_exported":679270,
  "energy_imported":817590,
  "instant_average_voltage":243.53333333333333,
  "instant_total_current":63,
  "i_a_current":0,
  "i_b_current":0,
  "i_c_current":0,
  "timeout":1500000000},
"load":
  {"last_communication_time":"2020-04-18T12:08:57.187708738-07:00",
  "instant_power":1135.123687456975,
  "instant_reactive_power":-207.97783434945234,
  "instant_apparent_power":1154.0193089401098,
  "frequency":60,
  "energy_exported":0,
  "energy_imported":1795053.746111111,
  "instant_average_voltage":121.69499969482422,
  "instant_total_current":9.327611572402613,
  "i_a_current":0,
  "i_b_current":0,
  "i_c_current":0,
  "timeout":1500000000},
"solar":
  {"last_communication_time":"2020-04-18T12:08:57.18782107-07:00",
  "instant_power":4057.6199951171875,
  "instant_reactive_power":-58.510000228881836,
  "instant_apparent_power":4058.0418239468145,
  "frequency":60,
  "energy_exported":1915009.211398323,
  "energy_imported":361.4552872122197,
  "instant_average_voltage":121.69499969482422,
  "instant_total_current":0,"i_a_current":0,"i_b_current":0,"i_c_current":0,"timeout":1500000000}
}
```
- https://tesla-gateway/api/powerwalls
```json
{
    "enumerating": false,
    "updating": false,
    "checking_if_offgrid": false,
    "running_phase_detection": false,
    "phase_detection_last_error": "no phase information",
    "bubble_shedding": false,
    "on_grid_check_error": "on grid check not run",
    "grid_qualifying": false,
    "grid_code_validating": false,
    "phase_detection_not_available": true,
    "powerwalls": [
        {
            "Type": "",
            "PackagePartNumber": "1092170-05-J",
            "PackageSerialNumber": "TG120010000361",
            "type": "acpw",
            "grid_state": "Grid_Uncompliant",
            "grid_reconnection_time_seconds": 0,
            "under_phase_detection": false,
            "updating": false,
            "commissioning_diagnostic": {
                "name": "Commissioning",
                "category": "InternalComms",
                "disruptive": false,
                "inputs": null,
                "checks": [
                    {
                        "name": "CAN connectivity",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.86333686-07:00",
                        "end_time": "2020-04-18T12:13:55.863340193-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Enable switch",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.863342527-07:00",
                        "end_time": "2020-04-18T12:13:55.86334486-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Internal communications",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.863347193-07:00",
                        "end_time": "2020-04-18T12:13:55.863349193-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Firmware up-to-date",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.863351527-07:00",
                        "end_time": "2020-04-18T12:13:55.863353527-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    }
                ]
            },
            "update_diagnostic": {
                "name": "Firmware Update",
                "category": "InternalComms",
                "disruptive": true,
                "inputs": null,
                "checks": [
                    {
                        "name": "Powerwall firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Battery firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Inverter firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Grid code",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    }
                ]
            },
            "bc_type": ""
        },
        {
            "Type": "",
            "PackagePartNumber": "1092170-05-J",
            "PackageSerialNumber": "TG120010001NYN",
            "type": "acpw",
            "grid_state": "Grid_Uncompliant",
            "grid_reconnection_time_seconds": 0,
            "under_phase_detection": false,
            "updating": false,
            "commissioning_diagnostic": {
                "name": "Commissioning",
                "category": "InternalComms",
                "disruptive": false,
                "inputs": null,
                "checks": [
                    {
                        "name": "CAN connectivity",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.863901188-07:00",
                        "end_time": "2020-04-18T12:13:55.863904521-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Enable switch",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.863906855-07:00",
                        "end_time": "2020-04-18T12:13:55.863909188-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Internal communications",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.863911521-07:00",
                        "end_time": "2020-04-18T12:13:55.863913521-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Firmware up-to-date",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.863915855-07:00",
                        "end_time": "2020-04-18T12:13:55.863917855-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    }
                ]
            },
            "update_diagnostic": {
                "name": "Firmware Update",
                "category": "InternalComms",
                "disruptive": true,
                "inputs": null,
                "checks": [
                    {
                        "name": "Powerwall firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Battery firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Inverter firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Grid code",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    }
                ]
            },
            "bc_type": ""
        },
        {
            "Type": "",
            "PackagePartNumber": "1092170-05-J",
            "PackageSerialNumber": "TG120010001PJH",
            "type": "acpw",
            "grid_state": "Grid_Uncompliant",
            "grid_reconnection_time_seconds": 0,
            "under_phase_detection": false,
            "updating": false,
            "commissioning_diagnostic": {
                "name": "Commissioning",
                "category": "InternalComms",
                "disruptive": false,
                "inputs": null,
                "checks": [
                    {
                        "name": "CAN connectivity",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.86436585-07:00",
                        "end_time": "2020-04-18T12:13:55.864369184-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Enable switch",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.864371517-07:00",
                        "end_time": "2020-04-18T12:13:55.864373517-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Internal communications",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.86437585-07:00",
                        "end_time": "2020-04-18T12:13:55.86437785-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    },
                    {
                        "name": "Firmware up-to-date",
                        "status": "fail",
                        "start_time": "2020-04-18T12:13:55.864381184-07:00",
                        "end_time": "2020-04-18T12:13:55.864383517-07:00",
                        "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                        "results": {},
                        "debug": {}
                    }
                ]
            },
            "update_diagnostic": {
                "name": "Firmware Update",
                "category": "InternalComms",
                "disruptive": true,
                "inputs": null,
                "checks": [
                    {
                        "name": "Powerwall firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Battery firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Inverter firmware",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    },
                    {
                        "name": "Grid code",
                        "status": "not_run",
                        "start_time": null,
                        "end_time": null,
                        "progress": 0,
                        "results": null,
                        "debug": null
                    }
                ]
            },
            "bc_type": ""
        }
    ],
    "has_sync": true,
    "sync": {
        "updating": false,
        "commissioning_diagnostic": {
            "name": "Commissioning",
            "category": "InternalComms",
            "disruptive": false,
            "inputs": null,
            "checks": [
                {
                    "name": "CAN connectivity",
                    "status": "fail",
                    "start_time": "2020-04-18T12:13:55.864634848-07:00",
                    "end_time": "2020-04-18T12:13:55.864638181-07:00",
                    "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                    "results": {},
                    "debug": {}
                },
                {
                    "name": "Firmware up-to-date",
                    "status": "fail",
                    "start_time": "2020-04-18T12:13:55.864640848-07:00",
                    "end_time": "2020-04-18T12:13:55.864642848-07:00",
                    "message": "Cannot perform this action with site controller running. From landing page, either \"STOP SYSTEM\" or \"RUN WIZARD\" to proceed.",
                    "results": {},
                    "debug": {}
                }
            ]
        },
        "update_diagnostic": {
            "name": "Firmware Update",
            "category": "InternalComms",
            "disruptive": true,
            "inputs": null,
            "checks": [
                {
                    "name": "Synchronizer firmware",
                    "status": "not_run",
                    "start_time": null,
                    "end_time": null,
                    "progress": 0,
                    "results": null,
                    "debug": null
                },
                {
                    "name": "Grid code",
                    "status": "not_run",
                    "start_time": null,
                    "end_time": null,
                    "progress": 0,
                    "results": null,
                    "debug": null
                }
            ]
        }
    },
    "states": []
}
```
- https://tesla-gateway/api/sitemaster
```json
{"status":"StatusUp","running":true,"connected_to_tesla":true}
```

**Comment by ocalvo** [comment] 2020-04-18 19:23
Here is the app.XXXX.js:

**Comment by jrester** [comment] 2020-04-19 09:47
Great thanks! That helps alot!

**Comment by mago-kamar** [comment] 2020-04-22 09:20
Hello,
sorry but I'm lost looking from my previous opened issue and this new one.

The fix has been released?

Thanks a lot

**Comment by jrester** [comment] 2020-04-22 09:28
@mago-kamar The fix for the unique_ids problem should be integrated in version Homeassistant 0.108.8. 
I am currently working on adding support for powerwall version 1.46.0 to Homeassistant.

**Comment by mago-kamar** [comment] 2020-04-22 10:50
> @mago-kamar The fix for the unique_ids problem should be integrated in Homeassistant as of version 0.108.8.
> I am currently working on adding support for powerwall version 1.46.0 to Homeassistant.

Perfect @jrester ,
thank you very much

**Comment by mago-kamar** [comment] 2020-04-22 14:56
Hi @jrester ,
I installed the 0.108.8, but the issue is still present.
I uninstalled the integration, and then I installed it again, but it doesn't work ... I have the same problem.

Thanks,

Enrico

**Comment by jrester** [comment] 2020-04-22 15:15
You mean that no entities show up?

**Comment by mago-kamar** [comment] 2020-04-22 15:35
> You mean that no entities show up?

Exactly :(

**Comment by ocalvo** [comment] 2020-04-22 15:37
> > You mean that no entities show up?
> 
> Exactly :(

Can you browse to your Tesla gateway website? What version do you see in the bottom?

**Comment by mago-kamar** [comment] 2020-04-22 15:41
1.45.2

**Comment by jrester** [comment] 2020-04-22 15:42
Could you reopen the other issue and post your logs there?

**Comment by mago-kamar** [comment] 2020-04-22 15:43
> Could you reopen the other issue and post your logs there?

ok

**Comment by jrester** [comment] 2020-04-23 10:49
Should be closed by [34545](https://github.com/home-assistant/core/pull/34545).

**Closed** 2020-04-23 10:50 UTC
